---
- name: Run Podcast TTS API with GPU support
  hosts: windowsLOQ
  become: yes

  vars_files:
    - tts_conf.yml
  
  tasks:
    # - name: Check if the image exists
    #   shell: docker images -q pod_tts:latest
    #   register: image_exists
    #   ignore_errors: yes

    # - name: Set image existence fact
    #   set_fact:
    #     image_found: "{{ image_exists.stdout != '' }}"

    # - name: Debug image existence
    #   debug:
    #     msg: "Image exists: {{ image_found }}"

    - name: Run Docker container with GPU
      docker_container:
        name: "{{container_name}}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        runtime: nvidia

        env: "{{ env_vars }}"
        
        ports: "{{ports}}"
        
        volumes: "{{volumes}}"

        auto_remove: yes

        entrypoint: "{{entrypoint}}"

        detach: yes