---
- name: Run Podcast TTS API with GPU support
  hosts: localhost
  become: yes

  tasks:

    - name: Check if the image exists
      shell: docker images -q pod_tts:latest
      register: image_exists
      ignore_errors: yes

    - name: Set image existence fact
      set_fact:
        image_found: "{{ image_exists.stdout != '' }}"

    - name: Debug image existence
      debug:
        msg: "Image exists: {{ image_found }}"

    - name: Run Docker container with GPU
      docker_container:
        name: TTS_container
        image: pod_tts
        state: started
        runtime: nvidia

        env:
          NVIDIA_VISIBLE_DEVICES: all
        
        ports:
          - "9000:9000"
        
        volumes:
          - "/mnt/c/Users/Amr/AppData/Local/tts:/root/.local/share/tts"
          - "/mnt/c/Users/Amr/Music:/out"

        auto_remove: yes

        entrypoint: python3 tts_api.py

        detach: yes